name: golangci-lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false

      - uses: actions/checkout@v3

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        # with:
        #   version: v6.1.1

        #   # Optional: golangci-lint command line arguments.
        #   args: --enable-all --disable misspell --disable funlen --disable gofumpt --disable ireturn --disable cyclop --disable lll --disable gosec --disable gochecknoglobals --disable paralleltest --disable wsl --disable gocognit

      